# 01: Exploratory Data Analysis (EDA)
Project Statistika Inferensi TIF-SI-B 2024 Kelompok 8.

Anggota:
1. Ahmad Zaki
2. Arion Syemael Siahaan
3. Rayhan Egar Sadtya Nugraha

## Data Read

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('../data/SI-B Dataset 3 Project.csv')
df.head()

,Image Name,meanR,meanG,meanB,stdR,stdG,stdB,skewR,skewG,skewB,...,ASM-1-90,dissimilarity-1-90,contrast-1-135,energy-1-135,homogeneity-1-135,correlation-1-135,ASM-1-135,dissimilarity-1-135,class,Class
0,ijo2pa1.jpg,17.395776,18.057278,4.548844,40.818315,42.747400,15.235375,2.080558,2.117612,4.194824,...,0.011467,1.442313,25.495182,0.094406,0.596762,0.993697,0.008912,1.723876,11,1
1,ijo2pa10.jpg,17.048930,17.143965,4.285857,41.389466,42.116279,14.243516,2.185737,2.233318,4.195780,...,0.008959,1.323746,19.458658,0.083524,0.601338,0.994707,0.006976,1.618708,11,1
2,ijo2pa100.jpg,19.957301,16.498584,5.082156,48.724795,40.816921,15.203335,2.169338,2.245723,3.863509,...,0.009252,1.107091,19.837377,0.084084,0.603311,0.994233,0.007070,1.425450,11,1
3,ijo2pa101.jpg,19.713066,18.029258,4.707696,47.484912,43.629222,14.230307,2.135099,2.147982,3.987222,...,0.008969,1.050541,17.983701,0.082048,0.596238,0.994426,0.006732,1.375565,11,1
4,ijo2pa102.jpg,17.383914,14.581238,4.632718,46.006665,38.900382,14.446719,2.417031,2.458251,3.903999,...,0.009931,0.977596,13.670599,0.087442,0.621051,0.994895,0.007646,1.252951,11,1

In [15]:
numeric_feats = df.select_dtypes(include=['float64', 'int64'])
numeric_feats.drop(columns=['class', 'Class'], inplace=True)
numeric_feats

,meanR,meanG,meanB,stdR,stdG,stdB,skewR,skewG,skewB,kurR,...,homogeneity-1-90,correlation-1-90,ASM-1-90,dissimilarity-1-90,contrast-1-135,energy-1-135,homogeneity-1-135,correlation-1-135,ASM-1-135,dissimilarity-1-135
0,17.395776,18.057278,4.548844,40.818315,42.747400,15.235375,2.080558,2.117612,4.194824,2.786645,...,0.661221,0.994862,0.011467,1.442313,25.495182,0.094406,0.596762,0.993697,0.008912,1.723876
1,17.048930,17.143965,4.285857,41.389466,42.116279,14.243516,2.185737,2.233318,4.195780,3.243245,...,0.668268,0.995726,0.008959,1.323746,19.458658,0.083524,0.601338,0.994707,0.006976,1.618708
2,19.957301,16.498584,5.082156,48.724795,40.816921,15.203335,2.169338,2.245723,3.863509,3.069086,...,0.677613,0.996042,0.009252,1.107091,19.837377,0.084084,0.603311,0.994233,0.007070,1.425450
3,19.713066,18.029258,4.707696,47.484912,43.629222,14.230307,2.135099,2.147982,3.987222,2.920590,...,0.678148,0.996255,0.008969,1.050541,17.983701,0.082048,0.596238,0.994426,0.006732,1.375565
4,17.383914,14.581238,4.632718,46.006665,38.900382,14.446719,2.417031,2.458251,3.903999,4.259136,...,0.694110,0.996391,0.009931,0.977596,13.670599,0.087442,0.621051,0.994895,0.007646,1.252951
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5651,9.639953,10.066067,3.723893,30.483106,31.889883,13.215059,2.992953,2.998821,4.248670,7.465886,...,0.731947,0.996868,0.011226,0.725780,7.150027,0.092747,0.656495,0.995965,0.008602,0.936422
5652,13.668622,14.771024,4.213619,36.393775,38.963387,14.905458,2.582813,2.486990,4.489599,5.639969,...,0.762744,0.998743,0.012265,0.689985,6.195821,0.099329,0.710111,0.998233,0.009866,0.839363
5653,8.400466,8.839484,3.206222,26.736850,28.164536,11.817830,3.006128,2.996293,4.830452,7.515368,...,0.724399,0.997622,0.011560,0.810050,8.340865,0.092990,0.640558,0.996755,0.008647,1.070910
5654,6.854176,7.180244,2.669827,23.889681,25.155812,10.683938,3.349365,3.382105,5.157558,9.783128,...,0.678691,0.995737,0.009698,0.917355,8.882472,0.086371,0.599516,0.994767,0.007460,1.164045
5655,14.702825,15.633670,4.717498,37.707117,40.000770,15.451875,2.359625,2.314493,4.277625,4.170651,...,0.716232,0.998023,0.011949,0.833826,8.839826,0.095925,0.648261,0.997388,0.009202,1.049950

In [16]:

nonnumeric_feats = df.select_dtypes(include=['object'])
nonnumeric_feats

         Image Name
0       ijo2pa1.jpg
1      ijo2pa10.jpg
2     ijo2pa100.jpg
3     ijo2pa101.jpg
4     ijo2pa102.jpg
...             ...
5651   morotk79.jpg
5652    morotk8.jpg
5653   morotk80.jpg
5654   morotk81.jpg
5655    morotk9.jpg

[5656 rows x 1 columns]

In [18]:
df_id = df['Image Name'].copy()
df_target = df['Class'].copy()
df_data = df.drop(columns=['Image Name', 'Class']).copy()

In [19]:
df_data.shape

(5656, 79)